config/routes.rb
CustomerLoyalty::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'UserRegistrations' }
  resources :users
  devise_scope :user do
    match 'merchant/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'merchant' }
    match 'customer/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'customer' }
    match 'merchant/edit' => 'user_registrations#edit', :user => { :rolable_type => 'merchant' }
  end

  get 'customer/:id/generate_passbook' => 'customer#generate_passbook', :as => 'generate_passbook'
  get 'customer/:id/insecure_passbook' => 'customer#insecure_passbook', :as => 'generate_insecure_passbook'
  match "/customer/:id" => "customer#show", :as => 'customer_dashboard'
  post 'customer/:id/merchant_search' => 'customer#merchant_search', as: 'merchant_search'

  get 'merchant/:id/rewards_program' => 'merchant#rewards_program', :as => 'reward_program_details'
  put 'merchant/:id/rewards_program' => 'merchant#update_rewards_program', :as => 'update_reward_program'
  get 'merchant/print_signup_page' => 'merchant#print_signup_page', :as => 'print_signup_page'
  get 'merchant/loyalty_scan/:id' => 'merchant#loyalty_scan', :as => 'loyalty_scan'
  post 'merchant/earn' => 'merchant#earn', :as => 'earn'
  post 'merchant/redeem' => 'merchant#redeem', :as => 'redeem'

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.haml
.container
  .home-logo.center
    = image_tag 'LL-squarelandscape.png', size: '250x100'
  - if !current_user.nil?
    %h3.center
      Next Steps
    .home-instructions.center
      Thank you for registering!  Print a customer signup page or download a QR code that links to your signup page.
    %br/
    .center
      = link_to "Print Signup Page", print_signup_page_path
      %br
      = link_to "Download QR Code Graphic", generate_passbook_url(current_user.rolable_id) + ".svg", target: "_blank"
      %br
      = link_to "Sign out", destroy_user_session_path, method: :delete

  - if current_user.nil?
    .center
      %br/
      %br/
      = link_to "Sign in", new_user_session_path
      %br/
      = link_to "Customer sign up", customer_sign_up_path
      %br/
      = link_to "Merchant sign up", merchant_sign_up_path