config/routes.rb
CustomerLoyalty::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'UserRegistrations' }
  resources :users
  devise_scope :user do
    match 'merchant/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'merchant' }
    match 'customer/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'customer' }
    match 'merchant/edit' => 'user_registrations#edit', :user => { :rolable_type => 'merchant' }
  end

  get 'customer/:id/generate_passbook' => 'customer#generate_passbook', :as => 'generate_passbook'
  get 'customer/:id/insecure_passbook' => 'customer#insecure_passbook', :as => 'generate_insecure_passbook'
  match "/customer/:id" => "customer#show", :as => 'customer_dashboard'
  post 'customer/:id/merchant_search' => 'customer#merchant_search', as: 'merchant_search'

  get 'merchant/:id/rewards_program' => 'merchant#rewards_program', :as => 'reward_program_details'
  put 'merchant/:id/rewards_program' => 'merchant#update_rewards_program', :as => 'update_reward_program'
  get 'merchant/print_signup_page' => 'merchant#print_signup_page', :as => 'print_signup_page'
  get 'merchant/loyalty_scan/:id' => 'merchant#loyalty_scan', :as => 'loyalty_scan'
  post 'merchant/earn' => 'merchant#earn', :as => 'earn'
  post 'merchant/redeem' => 'merchant#redeem', :as => 'redeem'

  root :to => "home#index"
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_one :user, as: :rolable, dependent: :destroy
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses
  attr_accessible :addresses_attributes, :about, :reward_program_name,
    :reward_threshold_number, :reward_description

  validates :addresses, length: { minimum: 1 }

  delegate :email, to: :user
  delegate :name, to: :user
  delegate :phone_number, to: :user

  def user
    User.where(rolable_type: 'merchant', rolable_id: self.id).first
  end

  def address
    self.addresses.first.address_string
  end

  def self.find_by_search_params(params)
    return Merchant.all unless search_params_present?(params)
    [
      Merchant.find_by_users_name(params[:name]),
      Merchant.find_by_city(params[:city]),
      Merchant.find_by_zip(params[:zip])
    ].flatten
  end

  def self.search_params_present?(params)
    if params
      params[:name].present? || params[:city].present? || params[:zip].present?
    else
      false
    end
  end

  def self.find_by_users_name(name)
    Merchant.all.select { |m| m.user.name.downcase == name.downcase }
  end

  def self.find_by_city(city)
    Merchant.all.select { |m| m.addresses.any? { |a| a.city.downcase == city.downcase } }
  end

  def self.find_by_zip(zip)
    Merchant.all.select { |m| m.addresses.any? { |a| a.zip.downcase == zip.downcase } }
  end
end

app/controllers/merchant_controller.rb
class MerchantController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_merchant_logged_in

  def rewards_program
    @merchant = Merchant.find(current_user.rolable_id)
  end

  def update_rewards_program
    merchant = Merchant.find(params[:id])
    merchant.update_attributes(params[:merchant])
    redirect_to root_path, notice: "Reward program updated!"
  end

  def print_signup_page
    load_merchant
  end

  def load_merchant
    @merchant_user = User.find_by_id(current_user.id)
    @merchant = Merchant.find_by_id(@merchant_user.rolable_id)
    p @merchant_user
    p @merchant
  end
  def loyalty_scan
    @customer_user = User.find_by_id(params[:id])
    @customer = Customer.find_by_id(@customer_user.rolable_id)
    load_merchant
    @passbook = CustomerPassbook.find_by_customer_id_and_merchant_id(@customer_user.rolable_id, @merchant_user.rolable_id)
    p @passbook
  end

  def earn
    load_merchant
    @passbook = CustomerPassbook.find(params[:passbook_id])
    @passbook.balance += 1
    @passbook.save
    flash[:info] = "#{@merchant.earn_type.capitalize} earned"
    redirect_to loyalty_scan_path(params[:customer_id])
  end

  def redeem
    load_merchant
    @passbook = CustomerPassbook.find(params[:passbook_id])
    @passbook.balance -= @merchant.reward_threshold_number
    @passbook.save
    flash[:success] = "#{@merchant.reward_program_name} redeemed!"
    redirect_to loyalty_scan_path(params[:customer_id])
  end

  private

  def check_merchant_logged_in
    redirect_to new_user_session_path unless current_user.try(:rolable_type) == 'merchant'
  end
end

app/views/merchant/loyalty_scan.html.haml
%h2.center Customer Rewards
.container
  .center.nowrap
    .left-cell 
      Customer:
    .right-cell 
      = @customer_user.name
  .center.nowrap
    .left-cell
      = @merchant.earn_type.pluralize().capitalize()
      \: 
    .right-cell.passbook-balance
      = @passbook.balance
  %br/
  .button-div.center
    = form_tag(earn_path, id: 'earn_form') do
      = hidden_field_tag 'passbook_id', @passbook.id
      = hidden_field_tag 'customer_id', @customer.id
      = submit_tag "Earn Reward", class: "btn btn-large btn-primary"

  -if @passbook.balance >= @merchant.reward_threshold_number
    %h3.center Rewards Earned

    .center
      %hr.reward-separator{ align: "center" }
      .center.nowrap
        .reward-image
          &nbsp; 
          -#= image_tag "http://placehold.it/50x50"
        .reward-text.center
          = @merchant.reward_program_name
        .reward-points
          = pluralize(@merchant.reward_threshold_number, @merchant.earn_type)
      .button-div.center
        -#= link_to 'Redeem Reward', nil, class: 'btn btn-large btn-primary btn-success'
        = form_tag(redeem_path, id: 'earn_form') do
          = hidden_field_tag 'passbook_id', @passbook.id
          = hidden_field_tag 'customer_id', @customer.id
          = submit_tag "Redeem Reward", class: "btn btn-large btn-success"


-#%h3 Customer:
-#= debug(@customer) if user_session != nil
-#%h3 Customer user:
-#= debug(@customer_user) if user_session != nil
-#%h3 Merchant:
-#= debug(@merchant) if user_session != nil
-#%h3 current_user:
-#= debug(@current_user) if user_session != nil
-#%h3 passbook:
-#= debug(@passbook) if user_session != nil
-#= debug(@merchant.user) if user_session != nil

app/views/merchant/print_signup_page.html.haml
.print-signup.container
  %h2.center
    = @merchant_user.name
  .subtitle.center
    Scan our QR code to signup for our Rewards program!
  .qr.center
    = image_tag(generate_passbook_path(@merchant_user.id) + '.svg', size: '150x150')
  .signup_link.center
    = link_to generate_passbook_url(@merchant_user.id), generate_passbook_url(@merchant_user.id)

  .powered-by.center
    powered by 
    = image_tag "http://placehold.it/100x40"


-#%h3 Merchant:
-#= debug(@merchant) if user_session != nil
-#%h3 Merchant user:
-#= debug(@merchant_user) if user_session != nil

app/views/merchant/rewards_program.html.haml
%h2
  Update your rewards program

= simple_form_for @merchant, url: update_reward_program_path(@merchant) do |f|
  = f.input :reward_program_name
  = f.input :reward_threshold_number
  = f.input :reward_description

  = f.button :submit