config/routes.rb
CustomerLoyalty::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'UserRegistrations' }
  resources :users
  devise_scope :user do
    match 'merchant/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'merchant' }
    match 'customer/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'customer' }
    match 'merchant/edit' => 'user_registrations#edit', :user => { :rolable_type => 'merchant' }
  end

  get 'customer/:id/generate_passbook' => 'customer#generate_passbook', :as => 'generate_passbook'
  get 'customer/:id/insecure_passbook' => 'customer#insecure_passbook', :as => 'generate_insecure_passbook'
  match "/customer/:id" => "customer#show", :as => 'customer_dashboard'
  post 'customer/:id/merchant_search' => 'customer#merchant_search', as: 'merchant_search'

  get 'merchant/:id/rewards_program' => 'merchant#rewards_program', :as => 'reward_program_details'
  put 'merchant/:id/rewards_program' => 'merchant#update_rewards_program', :as => 'update_reward_program'
  get 'merchant/print_signup_page' => 'merchant#print_signup_page', :as => 'print_signup_page'
  get 'merchant/loyalty_scan/:id' => 'merchant#loyalty_scan', :as => 'loyalty_scan'
  post 'merchant/earn' => 'merchant#earn', :as => 'earn'
  post 'merchant/redeem' => 'merchant#redeem', :as => 'redeem'

  root :to => "home#index"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :rolable, dependent: :destroy
  has_many :customer_passbooks

  delegate :email, to: :user
  delegate :name, to: :user
  delegate :phone_number, to: :user

  def user
    User.where(rolable_type: 'customer', rolable_id: self.id).first
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_filter :authenticate_user!, :except => [:insecure_passbook]
  before_filter :check_client_logged_in, :except => [:insecure_passbook]

  def show
    @customer = Customer.find(current_user.rolable_id)
  end

  def merchant_search
    @merchants = Merchant.find_by_search_params(params[:search])
  end

  def insecure_passbook
    merchant = Merchant.find(params[:id])
    customer = FactoryGirl.create :customer
    passbook = Passbook::MerchantPassbook.new customer.id, merchant.id, loyalty_scan_url(merchant.id)
    user_agent = request.env['HTTP_USER_AGENT'].downcase
      send_data passbook.stream.string, type: 'application/vnd.apple.pkpass',
      disposition: 'attachment',
      filename: 'pass.pkpass'
      #PassbookMailer.send_passbook(customer, merchant, passbook).deliver
#      send_data passbook.stream.string, type: 'application/vnd.apple.pkpass', disposition: 'attachment', filename: "pass.pkpass"
    #redirect_to root_path, notice: "Passbook generated!"
  end

  def generate_passbook
    respond_to do |format|
      format.html do
        merchant = Merchant.find(params[:merchant_id])
        customer = Customer.find(current_user.rolable_id)
        passbook = Passbook::MerchantPassbook.new customer.id, merchant.id, loyalty_scan_url(merchant.id)
        user_agent = request.env['HTTP_USER_AGENT'].downcase
        if user_agent =~ /iphone/
          send_data passbook.stream, type: 'application/vnd.apple.pkpass',
          disposition: 'attachment',
          filename: 'pass.pkpass'
        else
          #PassbookMailer.send_passbook(customer, merchant, passbook).deliver
          send_data passbook.stream.string, type: 'application/vnd.apple.pkpass', disposition: 'attachment', filename: "pass.pkpass"
        end
        #redirect_to root_path, notice: "Passbook generated!"
      end
      format.svg { render :qrcode => generate_insecure_passbook_url(params[:id]) }
    end
  end

  private

  def check_client_logged_in
    redirect_to new_user_session_path unless current_user.try(:rolable_type) == 'customer' or params[:format] == 'svg'
  end
end

app/views/customer/_form.html.haml
= form_for :search, url: merchant_search_path, method: :post do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :city
    = f.text_field :city
  %p
    = f.label :zip
    = f.text_field :zip
  %p
    = f.submit "Search"

app/views/customer/merchant_search.html.haml
%h1
  Discover merchants

= render 'form'

%p
  = link_to "Back", customer_dashboard_path(current_user.rolable_id)

- if @merchants.present?
  - @merchants.each do |merchant|
    %strong
      Merchant: #{merchant.name}
    %p
      Address: #{merchant.address}
    %p
      = link_to "Download Passbook", generate_passbook_path(id: current_user.rolable_id, merchant_id: merchant.id)
    %br
- else
  %p
    No merchants match your search. Please try different search terms.

app/views/customer/show.html.haml
%h1
  Welcome #{@customer.name}!

%p
  = link_to "Find Merchants", merchant_search_path, method: :post

- if @customer.customer_passbooks.empty?
  %p
    You don't have any passbooks!
- else
  %h3
    Your Passbooks:
  -@customer.customer_passbooks.each do |passbook|
    -merchant = passbook.merchant
    %h4
      #{merchant.name} passbook
    %p
      Reward program: #{merchant.reward_program_name}
    %p
      Reward description: #{merchant.reward_description}
    %p
      Reward threshold: #{merchant.reward_threshold_number}
    %strong
      Your current balance: #{passbook.balance}
    - if passbook.balance >= merchant.reward_threshold_number
      %br
      %strong
        You have unlocked this reward! Remember to redeem it next time you visit.