config/routes.rb
CustomerLoyalty::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'UserRegistrations' }
  resources :users
  devise_scope :user do
    match 'merchant/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'merchant' }
    match 'customer/sign_up' => 'user_registrations#new', :user => { :rolable_type => 'customer' }
    match 'merchant/edit' => 'user_registrations#edit', :user => { :rolable_type => 'merchant' }
  end

  get 'customer/:id/generate_passbook' => 'customer#generate_passbook', :as => 'generate_passbook'
  get 'customer/:id/insecure_passbook' => 'customer#insecure_passbook', :as => 'generate_insecure_passbook'
  match "/customer/:id" => "customer#show", :as => 'customer_dashboard'
  post 'customer/:id/merchant_search' => 'customer#merchant_search', as: 'merchant_search'

  get 'merchant/:id/rewards_program' => 'merchant#rewards_program', :as => 'reward_program_details'
  put 'merchant/:id/rewards_program' => 'merchant#update_rewards_program', :as => 'update_reward_program'
  get 'merchant/print_signup_page' => 'merchant#print_signup_page', :as => 'print_signup_page'
  get 'merchant/loyalty_scan/:id' => 'merchant#loyalty_scan', :as => 'loyalty_scan'
  post 'merchant/earn' => 'merchant#earn', :as => 'earn'
  post 'merchant/redeem' => 'merchant#redeem', :as => 'redeem'

  root :to => "home#index"
end

app/views/layouts/_header.html.haml
- if current_user.try(:is_merchant?)
  %header.navbar.navbar-fixed-top
    .navbar-inner
      .container
        -#.ll-logo
        = image_tag('LL-squareicon.png', size:'32x32', id:'ll-logo-img')
        =link_to "LocalLoyalty", '#', class: "brand"
        - if current_user
          .brand
            \|
          .brand #{current_user.name}
        %nav
          %ul.nav.pull-right
            %li= link_to "Home", root_path 
            - if current_user
              %li= link_to "Merchant Profile", merchant_edit_path
              %li= link_to "Edit Reward", reward_program_details_path(current_user.rolable_id)
              %li= link_to "Activity Report", nil
              %li= link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Sign in", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Customer Loyalty
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{ name: 'viewport', :content => 'width=device-width, initial-scale=1.0'}/
  %body
    = render 'layouts/header'
    .container
      - flash.each do |severity, message|
        = content_tag(:div, message, { class: "alert alert-#{severity}" })
      = yield
      -#= debug(params) if Rails.env.development?
      -#= debug(current_user) if current_user != nil